# Generated by Django 2.1.4 on 2019-01-03 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(max_length=30)),
                ('song_name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=30)),
                ('youtube', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Title'),
        ),
    ]
