# Generated by Django 2.1.4 on 2019-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20190103_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='title',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
